version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gymcore_backend
    environment:
      PORT: 3001
      NODE_ENV: development
      DATABASE_URL: "${DATABASE_URL}"
      SUPABASE_URL: "${SUPABASE_URL}"
      SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
      SUPABASE_JWT_SECRET: "${SUPABASE_JWT_SECRET}"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm run start:dev"
    restart: unless-stopped