version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gymcore_postgres
    environment:
      POSTGRES_DB: gymcore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gymcore_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: gymcore_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gymcore_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/gymcore_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: "super-secure-jwt-secret-for-docker"
      JWT_EXPIRES_IN: "7d"
      PORT: 3001
      NODE_ENV: development
      FRONTEND_URL: "http://localhost:3000"
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: gymcore_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: